name: dl-job
on:
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  dl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download file
        run: bash ./update.sh
