name: dl-job
on:
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:
  
jobs:
  dl:
    runs-on: ubuntu-latest
    steps:
      - name: download file
        run: curl https://files.opendatarchives.fr/professionnels.ign.fr/tree.json -o ./resources/opendatarchives.json
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
